# Generated by Django 4.1.7 on 2023-02-27 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
    ]
