# Generated by Django 4.1.7 on 2023-02-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='фамилия'),
        ),
    ]
